src/css/edit-view.scss, src/pages/edit_view/EditView.vue, src/pages/entities_view/components/ContextMenu.vue, src/repositories/scraper-repository/scrapers/dblp.ts, src/repositories/scraper-repository/scrapers/ieee.ts
=> + support book

src/pages/entities_view/EntitiesView.vue, src/pages/toolbar_view/ToolbarView.vue
=> Electron quicklook bug.

package.json, src/interactors/entity-interactor.ts, src/pages/toolbar_view/ToolbarView.vue, src/utils/preference.ts
=> + fix routine scrape

quasar.conf.js, quasar.conf.mac.js, quasar.conf.win.js, src-electron/electron-main.js, src/css/preference-view.scss, src/interactors/entity-interactor.ts, src/pages/Index.vue, src/pages/preference_view/components/CloudTab.vue, src/repositories/db-repository/db-init.ts, src/repositories/db-repository/db-repository.ts, src/utils/preference.ts
=> + custom atlas and pause sync

src/css/edit-view.scss, src/pages/Index.vue, src/pages/edit_view/CategorizerEditView.vue, src/pages/edit_view/EditView.vue, src/pages/edit_view/components/TextField.vue
=> + better categorizer UI, auto suggestion

src/pages/preference_view/components/ScraperTab.vue, src/repositories/scraper-repository/scraper-repository.ts, src/repositories/scraper-repository/scrapers/dblp.ts, src/repositories/scraper-repository/scrapers/openreview.ts, src/repositories/scraper-repository/scrapers/pdf.ts, src/utils/preference.ts
=> + openreview and iclr scraper

src/css/list-view.scss, src/pages/entities_view/components/ListView.vue
=> + better windows scroll bar

packages/main/files.ts, packages/preload/index_preview.ts, packages/preload/vite.config.ts, packages/renderer/index_preview.html, packages/renderer/src/Preview.vue, packages/renderer/src/global.d.ts, packages/renderer/src/main_preview.ts, packages/renderer/src/ui/preview-view.vue, packages/renderer/vite.config.ts
=> Windows Preview

package.json, packages/main/index.ts, packages/preload/models/PaperEntity.ts, packages/preload/models/PaperEntityDraft.ts, packages/preload/repositories/db-repository/db-crud.ts, packages/preload/repositories/db-repository/db-init.ts, packages/preload/repositories/db-repository/db-migration.ts, packages/preload/repositories/db-repository/db-repository.ts, packages/preload/repositories/exporter-repository/exporters/bib-exporter.ts, packages/preload/repositories/scraper-repository/scrapers/dblp.ts, packages/preload/repositories/scraper-repository/scrapers/doi.ts, packages/preload/repositories/scraper-repository/scrapers/ieee.ts, packages/preload/repositories/scraper-repository/scrapers/openreview.ts, packages/preload/repositories/web-importer-repository/importers/importer.ts, packages/renderer/src/ui/main-view/detail-view/components/pub-details.vue, packages/renderer/src/ui/main-view/detail-view/detail-view.vue, packages/renderer/src/ui/preference-view/components/toggle.vue, packages/renderer/src/ui/preference-view/preference-view.vue, packages/renderer/src/ui/preference-view/scraper-view.vue, packages/renderer/src/ui/whats-new-view.vue
1. Publication details.
2. Fix bugs.
=> Electron dev

.github/workflows/electron_dev.yml, .github/workflows/electron_e2e_test.yml
=> Update GitHub workflow

app/repositories/db-repository/paper-entity-repository.ts
=> add fuzzy search for general mode.

app/interactors/entity-interactor.ts, app/locales/locales/en.GB.json, app/locales/locales/zh.CN.json, app/main/win_main/contextmenu.ts, app/models/categorizer.ts, app/models/smart-filter.ts, app/renderer/ui/app-view.vue, app/renderer/ui/edit-view/components/smart-filter-rule-box.vue, app/renderer/ui/edit-view/smartfilter-edit-view.vue, app/renderer/ui/main-view/detail-view/components/categorizers.vue, app/renderer/ui/main-view/menubar-view/components/search-input.vue, app/renderer/ui/sidebar-view/sidebar-feeds-view.vue, app/renderer/ui/sidebar-view/sidebar-library-view.vue, app/repositories/db-repository/db-repository.ts, app/repositories/db-repository/paper-entity-repository.ts, app/repositories/db-repository/smartfilter-repository.ts, app/state/renderer/appstate.ts, app/state/states.ts, package-lock.json, package.json
=> New Feature: Smart Folders

app/locales/locales/en.GB.json
Thanks for making PaperLib. I fixed some grammar errors in the locale file. These are among the first sentences that users read when they start the software.
=> Update en.GB.json after a quick sanity check

README.md
Hi, I've restructured the readme for English in an attempt to make it more concise and easier to understand.
=> Better readme for English

app/renderer/ui/main-view/data-view/components/list-view/list-view.vue, app/renderer/ui/main-view/data-view/components/table-view/feed-table-view.vue, app/renderer/ui/main-view/data-view/components/table-view/table-view.vue, app/renderer/ui/main-view/main-view.vue
=> Fix #263: add auto scrolling when press arrow keys

app/main/services/upgrade-service.ts, app/renderer/ui/app-view.vue, app/renderer/ui/main-view/data-view/components/list-view/components/paper-list-item.vue
=> Fix: #279 render special char

app/renderer/ui/preference-view/cloud-view.vue, app/renderer/ui/preference-view/export-view.vue, app/renderer/ui/preference-view/extension-view.vue, app/renderer/ui/preference-view/preference-view.vue
1. Fix cloud-sync url
2. Fix some UI with `overflow-scroll` -> `scroll-y-auto`
3. Change close button
Before:
After:
=> Update URLs and fix some UI

app/renderer/ui/main-view/data-view/feed-data-view.vue, app/renderer/ui/main-view/data-view/paper-data-view.vue
=> Fix: #349 Add selectedID comparing before firing event.

app/renderer/ui/app-view.vue
=> Fix: disable space pressing's default scrolling.

app/renderer/services/querysentence-service.ts, app/renderer/ui/sidebar-view/sidebar-library-view.vue
=> Fix: #368 sidebar sort

app/extension/services/extension-management-service.ts
=> [Enahnce] Use an alternative npm url for China mainland user.

app/renderer/ui/sidebar-view/sidebar-library-view.vue
=> Fix: [BUG] Click All Papers should reset all filters #376

app/renderer/ui/edit-view/components/smart-filter-rule-box.vue
=> Fix: 'IN' smart filter error in issue#389

app/renderer/ui/edit-view/components/smart-filter-rule-box.vue
@Rccubc I modified some parts of your code to fix this bug.
=> Fix: #389 smartfilter UI bug when dealing with 'IN'

app/main/main-entry.ts
=> Implement: #137 API for other Apps.

app/main/services/menu-service.ts, app/renderer/ui/main-view/main-view.vue
=> Fix: scrolling when press space #403

app/renderer/ui/main-view/detail-view/components/supplementary.vue
=> Fix: #405 Cannot open supp

app/main/services/contextmenu-service.ts
=> Feat: register contextmenu from extensions

app/renderer/ui/main-view/data-view/paper-data-view.vue
=> Fix: #411 table-preview-related bugs

app/renderer/ui/sidebar-view/components/tree/item-row.vue, app/renderer/ui/sidebar-view/components/tree/tree-node.vue
=> Fix: #414 sidebar editing bug.

app/main/services/window-process-management-service.ts
=> Feat(window-service): implement utils

app/renderer/ui/sidebar-view/sidebar-view.vue
It's **not** a feature or bug, but a suggestion. Can we place the logo on the app header? :)
=> Suggestion: place the logo on the header

app/renderer/ui/main-view/menubar-view/window-menu-bar.vue
fix the locales UI bug in issue #422
=>  fix: locales UI bug in Chinese

app/renderer/services/feed-service.ts
=> Fix: #425 RSS deleting bug when the name contains special chars

app/main/services/menu-service.ts
=> Fix: [BUG] Cannot reopen paperlib after the window is closed with cmdw

app/renderer/ui/main-view/detail-view/components/rating.vue
=> Feat: support clear the rating

app/renderer/ui/sidebar-view/components/tree/tree-node.vue
=> Fix: sidebar label draggable bug(#436)

app/locales/locales/en.GB.json, app/locales/locales/zh.CN.json, app/main/services/contextmenu-service.ts, app/models/categorizer.ts, app/renderer/ui/main-view/data-view/paper-data-view.vue, app/renderer/ui/main-view/main-view.vue
=> Feat: #437 remove from categories(folder or tag)

app/base/url.ts, app/main/services/filesystem-service.ts, app/renderer/services/categorizer-service.ts, app/renderer/services/file-service.ts, app/renderer/services/paper-service.ts, app/renderer/services/reference-service.ts, app/renderer/ui/main-view/detail-view/components/thumbnail.vue, app/renderer/ui/main-view/detail-view/paper-detail-view.vue, app/renderer/ui/main-view/main-view.vue, app/renderer/ui/preference-view/cloud-view.vue, app/repositories/db-repository/paper-entity-repository.ts, app/repositories/db-repository/smartfilter-repository.ts, app/repositories/file-repository/backend.ts, app/repositories/file-repository/local-backend.ts, app/repositories/file-repository/webdav-backend.ts, package.json, pnpm-lock.yaml
1. Fix #440
2. Refector webdav backend.
3. Support subfolders in the appLibFolder.
=> Enhance: Better file beckends.

app/main/services/menu-service.ts, app/renderer/ui/preference-view/components/hotkey-options.vue
=> fix: global shortcuts not working

app/repositories/file-repository/webdav-backend.ts
=> Fix: [BUG] Webdav move file error.  #460

app/main/services/contextmenu-service.ts, app/renderer/services/reference-service.ts, app/renderer/ui/main-view/main-view.vue, paperlib-api/dist/api.d.ts
It seems to work, I have some code standards/contribution questions:
1. commit messages - seems to follow conventional commits- does capitalization matter? i.e. Feat or feat.
2. string utils - i used a capitalized function in the code i added, i saw other places defining the same function should i consolidate the function to some util or at base/string?
3. tests - some of the convertion logic im not sure I placed it in the correct place or it should be in some service and if so maybe i can add tests?
4. The conversion logic i took from the repo that was suggested in #458  added a comment there pointing to the file i took the code from, is it better to use a different comment format or remove it? if you know of a better/more elegant way to convert it let me know il make changes as needed
=> Feat: BibItem export #458

app/renderer/ui/main-view/main-view.vue
=> feat(shortcuts): select all entities

app/renderer/services/shortcut-service.ts, app/renderer/ui/main-view/main-view.vue
=> fix(shortcuts): space key not working in input

app/renderer/services/paper-service.ts
=> fix: add to categorizer #515

app/renderer/services/render-service.ts, app/renderer/ui/app-view.vue, app/renderer/ui/main-view/data-view/components/list-view/components/paper-list-item.vue, app/renderer/ui/main-view/data-view/components/table-view/components/table-item.vue, app/renderer/ui/main-view/detail-view/feed-detail-view.vue, app/renderer/ui/main-view/detail-view/paper-detail-view.vue, app/renderer/ui/preference-view/mainview-view.vue
=> feat: render latex in title

app/main/services/contextmenu-service.ts, app/renderer/services/file-service.ts, app/renderer/services/paper-service.ts, app/renderer/ui/edit-view/components/smart-filter-rule-box.vue, app/renderer/ui/main-view/detail-view/components/supplementary.vue, app/renderer/ui/main-view/detail-view/paper-detail-view.vue, app/repositories/db-repository/paper-entity-repository.ts
=> feat: #177 custom sup name

app/common/utils.ts, app/renderer/services/uistate-service.ts, app/renderer/ui/app-view.vue, app/renderer/ui/main-view/main-view.vue, app/renderer/ui/sidebar-view/components/tree/tree-node.vue, app/renderer/ui/sidebar-view/components/tree/tree-root.vue, app/renderer/ui/sidebar-view/sidebar-library-view.vue, app/renderer/ui/sidebar-view/sidebar-view.vue
=> feat: select categorizers jointly

app/renderer/ui/edit-view/components/codes-input.vue
=> fix: code editing bug

app/main/services/window-process-management-service.ts, app/renderer/ui/preference-view/mainview-view.vue
1. remove custom css UI
2. put css files in the config dir to setup custom css.
=> Fix: custom css
